name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download Dependencies
        run: ./gradlew androidDependencies
      - name: Run ktlint
        run: ./gradlew ktlintCheck
      - name: Run detekt
        run: ./gradlew detekt
      - name: Run UnitTest
        run: ./gradlew test
      - name: Android Test Report Action
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
